PI = 3.1415926535897934

DEFAULT_SCREEN_WIDTH = 700
DEFAULT_SCREEN_HEIGHT = 700

SCREEN_WIDTH = DEFAULT_SCREEN_WIDTH
SCREEN_HEIGHT = DEFAULT_SCREEN_HEIGHT

PROJ_BORDER = 150
P_PROJ_DAMAGE_MULT = 1
E_PROJ_DAMAGE_MULT = 1

P_HEALTH = 10
P_SPEED = 150
P_SIZE = 15
P_PROJ_SPEED = 550

E_HEALTH = 200
E_SPEED = 60
E_PROJ_BORDER = 2

#Pattern settings

RADIAL_COUNT_N = 30
RADIAL_DELAY_N = .5
RADIAL_SPEED_N = 180

SPIN_COUNT_N = 30
SPIN_DELAY_N = .55
SPIN_SPEED_N = 250

RANDOM_COUNT_N = 25
RANDOM_DELAY_N = .25
RANDOM_SPEED_N = 225

RAIN_COUNT_N = 10
RAIN_DELAY_N = .2
RAIN_SPEED_N = 325



RADIAL_COUNT = RADIAL_COUNT_N
RADIAL_DELAY = RADIAL_DELAY_N
RADIAL_SPEED = RADIAL_SPEED_N

SPIN_COUNT = SPIN_COUNT_N
SPIN_DELAY = SPIN_DELAY_N
SPIN_SPEED = SPIN_SPEED_N

RANDOM_COUNT = RANDOM_COUNT_N
RANDOM_DELAY = RANDOM_DELAY_N
RANDOM_SPEED = RANDOM_SPEED_N

RAIN_COUNT = RAIN_COUNT_N
RAIN_DELAY = RAIN_DELAY_N
RAIN_SPEED = RAIN_SPEED_N

TRACKING_COUNT = 15
TRACKING_DELAY = .3
TRACKING_SPEED = 280
TRACKING_SPAN = PI*1.6
